import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
	buildIssueBody,
	generateIssueUrl,
	getBuildInfo,
	getDeviceInfo,
	getGitHubLinks,
	getRepoUrl,
	openBugReport,
} from "./githubService";

describe("githubService", () => {
	describe("getRepoUrl", () => {
		it("returns default repo URL", () => {
			const url = getRepoUrl();
			expect(url).toBe("https://github.com/idvorkin/humane-tracker-1");
		});
	});

	describe("getGitHubLinks", () => {
		it("generates correct links from repo URL", () => {
			const links = getGitHubLinks("https://github.com/user/repo");
			expect(links).toEqual({
				repo: "https://github.com/user/repo",
				issues: "https://github.com/user/repo/issues",
				newIssue: "https://github.com/user/repo/issues/new",
			});
		});

		it("removes .git suffix from repo URL", () => {
			const links = getGitHubLinks("https://github.com/user/repo.git");
			expect(links).toEqual({
				repo: "https://github.com/user/repo",
				issues: "https://github.com/user/repo/issues",
				newIssue: "https://github.com/user/repo/issues/new",
			});
		});

		it("uses default repo URL when none provided", () => {
			const links = getGitHubLinks();
			expect(links.repo).toBe("https://github.com/idvorkin/humane-tracker-1");
		});
	});

	describe("getDeviceInfo", () => {
		it("returns formatted device info string", () => {
			const info = getDeviceInfo();
			expect(info).toContain("**Platform:**");
			expect(info).toContain("**User Agent:**");
			expect(info).toContain("**Language:**");
			expect(info).toContain("**Screen:**");
			expect(info).toContain("**Device Memory:**");
			expect(info).toContain("**CPU Cores:**");
			expect(info).toContain("**Online Status:**");
			expect(info).toContain("**Connection Type:**");
			expect(info).toContain("**Display Mode:**");
			expect(info).toContain("**Touch Device:**");
			expect(info).toContain("**Mobile:**");
		});
	});

	describe("getBuildInfo", () => {
		it("returns build info object with expected properties", () => {
			const info = getBuildInfo();
			expect(info).toHaveProperty("sha");
			expect(info).toHaveProperty("commitUrl");
			expect(info).toHaveProperty("branch");
			expect(info).toHaveProperty("timestamp");
		});

		it("returns valid git values", () => {
			const info = getBuildInfo();
			// Should always have real git values (generated by just dev/build)
			expect(info.sha).toMatch(/^[a-f0-9]{40}$/); // Full SHA
			expect(info.commitUrl).toContain("github.com");
			expect(info.commitUrl).toContain(info.sha);
		});
	});

	describe("buildIssueBody", () => {
		it("builds body without metadata", () => {
			const body = buildIssueBody("Something broke", false);

			expect(body).toContain("## Description");
			expect(body).toContain("Something broke");
			expect(body).not.toContain("## Environment");
			expect(body).not.toContain("## Device Info");
		});

		it("builds body with metadata", () => {
			const body = buildIssueBody("Something broke", true);

			expect(body).toContain("## Description");
			expect(body).toContain("Something broke");
			expect(body).toContain("## Environment");
			expect(body).toContain("**Date:**");
			expect(body).toContain("**Version:**");
			expect(body).toContain("## Device Info");
		});

		it("handles empty description", () => {
			const body = buildIssueBody("", false);
			expect(body).toContain("_No description provided_");
		});

		it("includes screenshot note when hasScreenshot is true", () => {
			const body = buildIssueBody("Bug description", false, true);
			expect(body).toContain("## Screenshot");
			expect(body).toContain("copied to clipboard");
		});
	});

	describe("generateIssueUrl", () => {
		it("generates URL with title and body parameters", () => {
			const url = generateIssueUrl({
				title: "Bug: Something broke",
				description: "It's broken",
				includeMetadata: false,
			});

			expect(url).toContain("/issues/new?");
			expect(url).toContain("title=Bug%3A+Something+broke");
			expect(url).toContain("labels=bug%2Cfrom-app");
		});

		it("uses default title when none provided", () => {
			const url = generateIssueUrl({
				title: "",
				description: "Something happened",
				includeMetadata: false,
			});

			expect(url).toContain("title=Bug+Report");
		});

		it("includes body content in URL", () => {
			const url = generateIssueUrl({
				title: "Test Bug",
				description: "This is a test",
				includeMetadata: false,
			});

			expect(url).toContain("body=");
			expect(url).toContain("This+is+a+test");
		});
	});

	describe("openBugReport", () => {
		const mockClipboard = {
			write: vi.fn(),
			writeText: vi.fn(),
		};
		const mockWindowOpen = vi.fn();

		beforeEach(() => {
			// Mock ClipboardItem
			vi.stubGlobal(
				"ClipboardItem",
				class MockClipboardItem {
					constructor(public items: Record<string, Blob>) {}
				},
			);
			vi.stubGlobal("navigator", {
				...navigator,
				clipboard: mockClipboard,
			});
			// Mock window.open
			window.open = mockWindowOpen;
		});

		afterEach(() => {
			vi.clearAllMocks();
			vi.unstubAllGlobals();
		});

		it("does not touch clipboard when no screenshot provided", async () => {
			await openBugReport({
				title: "Test Bug",
				description: "Bug description",
				includeMetadata: false,
			});

			expect(mockClipboard.write).not.toHaveBeenCalled();
			expect(mockClipboard.writeText).not.toHaveBeenCalled();
		});

		it("copies screenshot to clipboard when screenshot is provided", async () => {
			// Create a simple valid PNG data URL (1x1 transparent pixel)
			const pngDataUrl =
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";

			mockClipboard.write.mockResolvedValue(undefined);

			await openBugReport({
				title: "Test Bug",
				description: "Bug description",
				includeMetadata: false,
				screenshot: pngDataUrl,
			});

			expect(mockClipboard.write).toHaveBeenCalledTimes(1);
			const clipboardItems = mockClipboard.write.mock.calls[0][0];
			expect(clipboardItems).toHaveLength(1);
		});

		it("opens GitHub issue URL", async () => {
			await openBugReport({
				title: "Test Bug",
				description: "Bug description",
				includeMetadata: false,
			});

			expect(mockWindowOpen).toHaveBeenCalledWith(
				expect.stringContaining("/issues/new?"),
				"_blank",
				"noopener,noreferrer",
			);
		});

		it("returns the issue body", async () => {
			const body = await openBugReport({
				title: "Test Bug",
				description: "Bug description",
				includeMetadata: false,
			});

			expect(body).toContain("## Description");
			expect(body).toContain("Bug description");
		});
	});
});
